# Generated by Django 5.0.6 on 2024-06-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('manicura', 'Manicura'), ('pedicura', 'Pedicura'), ('otros', 'Otros')], max_length=20, null=True),
        ),
    ]
